### ISSUE TITLE
[Feature Request] Use GitHub Actions/Workflow instead AzureDevOps

### ISSUE THREAD

**Issue by dneto82** [almenscorner/intunecd-monitor#19]
For people and companies that don't have AzureDevOps, would be nice have options to use only GitHub Actions/Workflow to deploy IntuneCD Frontend also.

Thanks for you amazing job on intune automations. 

Regards,

**Comment by almenscorner** [comment]
Hi,

This is something I am looking into and want to support. If you look at my screen shot in #7, I have started to look at different ways of configuring the repos you're using and adding multi-tenant support. My plan with this is to clone and work with the repo inside the Docker container instead of using API's to support different locations. The IntuneCD Backup and Update is then also running in the Docker container, doing that I don't have to worry about API's and the git repo can be stored wherever you'd like

**Comment by almenscorner** [comment]
It has been a long time coming, but I'm happy to announce improvements are coming to Monitor soon: https://www.linkedin.com/posts/tobiasalmen_intunecd-docker-mvpbuzz-activity-7105888175847346176-xTl_?utm_source=share&utm_medium=member_desktop
