### ISSUE TITLE
Your deployment failed

### ISSUE THREAD

**Issue by KYHS-BOX** [almenscorner/intunecd-monitor#24]
During Template Deployment I've received this error during a role assignment:

ERROR TYPE
Principals of type Application cannot validly be used in role assignments. (Code: PrincipalTypeNotSupported)

![image](https://github.com/almenscorner/intunecd-monitor/assets/75421234/b5096fc7-ea74-4018-b739-ba63ec7e8439)

Do you know how to fix this?
thx
René.

**Comment by almenscorner** [comment]
It sounds like you provided the Client ID instead of the actual object ID, that can cause this error. You can give the SP permissions to the key vault manually by going to Access control (IAM) on your key vault and under role assignments assign your app registration to the "Key Vault Administrator" role.

**Comment by KYHS-BOX** [comment]
Thanks, that could be the issue, although I double checked the id's beforehand its possible that I mixed something up with the wrong id's. I will re-deploy template or update the role assignment in the keyvault manually. Thanks a lot for your quick reply.

**Comment by almenscorner** [comment]
Let me know if you're able to get through and deploy :)

**Comment by KYHS-BOX** [comment]
Now the deployment succeeded. As you mentioned I used the object ID from the app registration blade instead of the enterprise application object id.  Thanks again, we can close this issue as solved. 
Best regards.
René van den Wijngaard.
